function Apply(list, f, iter)
	iter = iter or ipairs
	for k, v in iter(list) do
		f(v, k)
	end
end

Apply({
	"System",
	"Renderer",
	"Sprite",
	"Texture",
	"Vector",
	"Time",
	"Keyboard",
	"Sound",
},
	function(v) LoadLibrary(v) end)

Apply({
	"Util.lua",
	"Panel.lua",
	"Textbox.lua",
	"Selection.lua",
	"ProgressBar.lua",
	"Scrollbar.lua",
	"StateStack.lua",
	"FadeState.lua",
	"Tween.lua",
	"StateMachine.lua",
	"Layout.lua",
	"StartMenuState.lua",
	"SettingsMenuState.lua",
	"InGameMenuState.lua",
	"FrontMenuState.lua",
	"TransactionState.lua",
	"ItemDB.lua",
	"ArmorItemDB.lua",
	"World.lua",
	"RumorMenuState.lua",
	"RumorDB.lua",
	"RumorImages.lua",
	"ShopOpenState.lua",
	"Day.lua",
	"Stats.lua",
	"Dice.lua",
	"Actor.lua",
	"HeroDB.lua",
	"CurrentHeroes.lua",
	"StatDefs.lua",
	"LevelFunction.lua",
	"ActorSummary.lua",
	"HeroStatusFrontMenuState.lua",
	"StoryBoard.lua",
	"StoryBoardEvents.lua",
	"ScreenState.lua",
	"CaptionState.lua",
	"CaptionStyles.lua",
	"TitleScreenState.lua",
	"intro.lua",
	"testcutscene.lua",
	"BackdropState.lua",
	"VendorState.lua",
	"CustomerState.lua",
	"Item.lua",
	"Encounter.lua",
	"InventoryState.lua",
	"Vendor.lua",
	"VendorSummary.lua",
	"VillageItemDB.lua",
	"VendorDB.lua",
	"VillagerState.lua",
	"DefaultGameState.lua",
	"Village.lua",
	"GossipDB.lua",
	"Adventure.lua",
	"SkillsDB.lua",
	},
	function(v) Asset.Run(v) end)